from typing import Protocol

from lab.fast_API.src.domain.entities import Order, User
from lab.fast_API.src.domain.events import DomainEvent


class OrderRepositoryPort(Protocol):
    def add(self, order: Order) -> Order: ...
    def get(self, order_id: int) -> Order | None: ...
    def list_by_user(self, user_id: int) -> list[Order]: ...
    def update_status(self, order_id: int, status: str) -> Order | None: ...
    def delete(self, order_id: int) -> bool: ...


class UserRepositoryPort(Protocol):
    def add(self, user: User) -> User: ...
    def get_by_username(self, username: str) -> User | None: ...
    def get_by_id(self, user_id: int) -> User | None: ...


class UnitOfWorkPort(Protocol):

    orders: OrderRepositoryPort
    users: UserRepositoryPort

    def __enter__(self) -> "UnitOfWorkPort": ...
    def __exit__(self, exc_type, exc_val, exc_tb) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...


class EventDispatcherPort(Protocol):
    def dispatch(self, events: list[DomainEvent]) -> None: ...


class PasswordHasherPort(Protocol):
    def hash(self, password: str) -> str: ...
    def verify(self, password: str, hashed: str) -> bool: ...


class TokenProviderPort(Protocol):
    def create_token(self, subject: str) -> str: ...
    def decode_token(self, token: str) -> str:
        ...
